"""fix_participant_constraints

Revision ID: 20e71f56feb4
Revises: 4247da9a39dc
Create Date: 2025-08-23 13:06:29.397448

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "20e71f56feb4"
down_revision: Union[str, Sequence[str], None] = "4247da9a39dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Safely drop test_users table if it exists
    try:
        op.drop_table("test_users")
    except Exception:
        # Table doesn't exist, which is fine
        pass
    
    # Drop existing constraints if they exist
    try:
        op.drop_constraint(op.f("uq_room_agent"), "participants", type_="unique")
    except Exception:
        # Constraint doesn't exist, which is fine
        pass
    
    try:
        op.drop_constraint(op.f("uq_room_user"), "participants", type_="unique")
    except Exception:
        # Constraint doesn't exist, which is fine
        pass
    
    op.create_index(
        "idx_room_agent_unique",
        "participants",
        ["room_id", "agent_profile_id"],
        unique=True,
        postgresql_where="agent_profile_id IS NOT NULL",
    )
    op.create_index(
        "idx_room_user_unique",
        "participants",
        ["room_id", "user_id"],
        unique=True,
        postgresql_where="user_id IS NOT NULL",
    )
    op.alter_column(
        "rooms",
        "settings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rooms",
        "settings",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    
    # Drop indexes if they exist
    try:
        op.drop_index(
            "idx_room_user_unique",
            table_name="participants",
            postgresql_where="user_id IS NOT NULL",
        )
    except Exception:
        pass
    
    try:
        op.drop_index(
            "idx_room_agent_unique",
            table_name="participants",
            postgresql_where="agent_profile_id IS NOT NULL",
        )
    except Exception:
        pass
    
    # Create constraints if they don't exist
    try:
        op.create_unique_constraint(
            op.f("uq_room_user"),
            "participants",
            ["room_id", "user_id"],
            postgresql_nulls_not_distinct=False,
        )
    except Exception:
        pass
    
    try:
        op.create_unique_constraint(
            op.f("uq_room_agent"),
            "participants",
            ["room_id", "agent_profile_id"],
            postgresql_nulls_not_distinct=False,
        )
    except Exception:
        pass
    
    # Create test_users table if it doesn't exist
    try:
        op.create_table(
            "test_users",
            sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
            sa.Column(
                "username", sa.VARCHAR(length=50), autoincrement=False, nullable=False
            ),
            sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
            sa.Column(
                "password_hash", sa.VARCHAR(length=255), autoincrement=False, nullable=False
            ),
            sa.Column(
                "display_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True
            ),
            sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
            sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
            sa.Column("role", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
            sa.Column(
                "created_at",
                postgresql.TIMESTAMP(timezone=True),
                server_default=sa.text("now()"),
                autoincrement=False,
                nullable=False,
            ),
            sa.PrimaryKeyConstraint("id", name=op.f("test_users_pkey")),
            sa.UniqueConstraint(
                "email",
                name=op.f("test_users_email_key"),
                postgresql_include=[],
                postgresql_nulls_not_distinct=False,
            ),
            sa.UniqueConstraint(
                "username",
                name=op.f("test_users_username_key"),
                postgresql_include=[],
                postgresql_nulls_not_distinct=False,
            ),
        )
    except Exception:
        pass
    # ### end Alembic commands ###
