"""fix_participant_constraints

Revision ID: 20e71f56feb4
Revises: 4247da9a39dc
Create Date: 2025-08-23 13:06:29.397448

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20e71f56feb4"
down_revision: str | Sequence[str] | None = "4247da9a39dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use raw SQL to check and drop test_users table safely
    connection = op.get_bind()

    # Check if test_users table exists and drop it
    result = connection.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'test_users'
        );
    """))
    if result.scalar():
        op.drop_table("test_users")

    # Check and drop constraints safely
    result = connection.execute(sa.text("""
        SELECT constraint_name 
        FROM information_schema.table_constraints 
        WHERE table_name = 'participants' 
        AND constraint_name = 'uq_room_agent';
    """))
    if result.fetchone():
        op.drop_constraint("uq_room_agent", "participants", type_="unique")

    result = connection.execute(sa.text("""
        SELECT constraint_name 
        FROM information_schema.table_constraints 
        WHERE table_name = 'participants' 
        AND constraint_name = 'uq_room_user';
    """))
    if result.fetchone():
        op.drop_constraint("uq_room_user", "participants", type_="unique")

    # Create new indexes
    op.create_index(
        "idx_room_agent_unique",
        "participants",
        ["room_id", "agent_profile_id"],
        unique=True,
        postgresql_where="agent_profile_id IS NOT NULL",
    )
    op.create_index(
        "idx_room_user_unique",
        "participants",
        ["room_id", "user_id"],
        unique=True,
        postgresql_where="user_id IS NOT NULL",
    )
    op.alter_column(
        "rooms",
        "settings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    op.alter_column(
        "rooms",
        "settings",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )

    # Check and drop indexes safely
    result = connection.execute(sa.text("""
        SELECT indexname 
        FROM pg_indexes 
        WHERE tablename = 'participants' 
        AND indexname = 'idx_room_user_unique';
    """))
    if result.fetchone():
        op.drop_index(
            "idx_room_user_unique",
            table_name="participants",
            postgresql_where="user_id IS NOT NULL",
        )

    result = connection.execute(sa.text("""
        SELECT indexname 
        FROM pg_indexes 
        WHERE tablename = 'participants' 
        AND indexname = 'idx_room_agent_unique';
    """))
    if result.fetchone():
        op.drop_index(
            "idx_room_agent_unique",
            table_name="participants",
            postgresql_where="agent_profile_id IS NOT NULL",
        )

    # Check and create constraints safely
    result = connection.execute(sa.text("""
        SELECT constraint_name 
        FROM information_schema.table_constraints 
        WHERE table_name = 'participants' 
        AND constraint_name = 'uq_room_user';
    """))
    if not result.fetchone():
        op.create_unique_constraint(
            "uq_room_user",
            "participants",
            ["room_id", "user_id"],
            postgresql_nulls_not_distinct=False,
        )

    result = connection.execute(sa.text("""
        SELECT constraint_name 
        FROM information_schema.table_constraints 
        WHERE table_name = 'participants' 
        AND constraint_name = 'uq_room_agent';
    """))
    if not result.fetchone():
        op.create_unique_constraint(
            "uq_room_agent",
            "participants",
            ["room_id", "agent_profile_id"],
            postgresql_nulls_not_distinct=False,
        )

    # Check and create test_users table safely
    result = connection.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'test_users'
        );
    """))
    if not result.scalar():
        op.create_table(
            "test_users",
            sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
            sa.Column(
                "username", sa.VARCHAR(length=50), autoincrement=False, nullable=False
            ),
            sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
            sa.Column(
                "password_hash", sa.VARCHAR(length=255), autoincrement=False, nullable=False
            ),
            sa.Column(
                "display_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True
            ),
            sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
            sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
            sa.Column("role", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
            sa.Column(
                "created_at",
                postgresql.TIMESTAMP(timezone=True),
                server_default=sa.text("now()"),
                autoincrement=False,
                nullable=False,
            ),
            sa.PrimaryKeyConstraint("id", name="test_users_pkey"),
            sa.UniqueConstraint(
                "email",
                name="test_users_email_key",
                postgresql_include=[],
                postgresql_nulls_not_distinct=False,
            ),
            sa.UniqueConstraint(
                "username",
                name="test_users_username_key",
                postgresql_include=[],
                postgresql_nulls_not_distinct=False,
            ),
        )
    # ### end Alembic commands ###
